spring.application.name=product-service
server.port=8080

############################ Keycloack Properties ##################################
keycloak-server-url=${KEYCLOACK_SERVER:http://localhost:8181}
realm=${KEYCLOACK_REALM:ecommerce-microservices-realm}
clientId=${KEYCLOACK_CLIENT_ID:ecommerce-client}

############################ MyBatis Properties ################################
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=NULL
mybatis.mapper-locations=classpath:**/mapper/*.xml

########################### Database Properties ###############################
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432/product?currentSchema=public}
spring.datasource.username=${DATASOURCE_USERNAME:postgre}
spring.datasource.password=${DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=${MAX_POOL_SIZE:10}
spring.datasource.hikari.connection-timeout=${CONNECTION_TIMEOUT:10000}
spring.datasource.hikari.minimum-idle=${MINIMUM_IDLE:1}
spring.datasource.hikari.idle-timeout=${IDLE_TIMEOUT:60000}
spring.datasource.hikari.max-lifetime=${MAX_LIFETIME:300000}

############################ Spring Security ##################################
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/ecommerce-microservices-realm
